
(function(){
"use strict";

function sh(a){return Array.from(a).sort(function(){return Math.random()-.5})}
function eh(s){return String(s).replace(/[&<>"']/g,function(m){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]})}
function vp(raw){var m=String(raw).match(/^(.*?)(?=[\u4e00-\u9fff])/);return m?{de:m[1].trim(),zh:String(raw).slice(m[1].length).trim()}:{de:String(raw).trim(),zh:""}}
function vk(v){return v.unit+"|"+v.raw}
function vs(){try{return JSON.parse(localStorage.getItem("DeutschTrainingLab_VocabMemory_v1")||"{}")}catch(e){return {}}}
function sv(x){localStorage.setItem("DeutschTrainingLab_VocabMemory_v1",JSON.stringify(x))}
function phrase(v){return /\s/.test(vp(v.raw).de)}
function mastery(x){if(!x)return 0;var a=(x.right||0)+(x.wrong||0);if(!a)return 0;return Math.max(0,Math.min(100,Math.round((x.right||0)/a*65+Math.min(x.streak||0,5)*7)))}
function pool(u){return FULL_VOCAB.filter(function(v){return (u==="ALL"||v.unit===u)&&vp(v.raw).zh})}
function hideGrammar(){var b=document.querySelector('[data-page="grammar"]');if(b)b.remove();var g=document.getElementById("grammar");if(g)g.remove()}
function visual(){var st=document.createElement("style");st.textContent="header{background:linear-gradient(135deg,#64766d,#8a8d9f,#a5a0ae)!important;padding:34px 18px 30px!important}nav{background:rgba(248,249,246,.94)!important;box-shadow:0 4px 18px rgba(45,55,50,.06)}.tab{color:#59645e!important}.tab.active{background:#dce3de!important;color:#43564c!important}.card{border-radius:20px!important;box-shadow:0 10px 30px rgba(49,61,54,.06)!important}.hero-card{background:linear-gradient(145deg,#fafbf7,#f1f4ef)}.eyebrow{font-size:11px;letter-spacing:.14em;color:#78857e;font-weight:700}.practice-config{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:18px 0}.practice-config label{display:block;font-size:13px;color:#6d7871;margin-bottom:5px}.grammar-summary{padding:14px 16px;border-radius:15px;background:#e9eee9;border:1px solid #d0d9d2;margin:15px 0}.grammar-chip{display:inline-block;margin:4px 5px 4px 0;padding:5px 9px;border-radius:99px;background:#f8faf7;border:1px solid #d0d8d1;font-size:13px}.logic-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.logic-grid>div{padding:14px;border-radius:15px;background:#f2f5f1;border:1px solid #dbe0db}.logic-grid b,.logic-grid span{display:block}.logic-grid span{color:#748078;font-size:14px;margin-top:4px}.translation-result{min-height:80px;margin-top:12px;padding:14px;border-radius:14px;background:#f2f5f1;border:1px solid #d5ddd6;white-space:pre-wrap}.translator-actions{display:flex;gap:9px;align-items:center;margin-top:10px;flex-wrap:wrap}@media(max-width:700px){.practice-config,.logic-grid{grid-template-columns:1fr}}";document.head.appendChild(st)}
function normalizeUnits(){FULL_VOCAB.forEach(function(v){if(v.unit==="E1–E5")v.unit="E5"})}

var UG={
E1:["人称代词第一格","规则动词现在时变位","sein 现在时变位","定/不定冠词第一格","句子类型与基本语序"],
E2:["kein- 第一格","不规则动词现在时变位","物主冠词第一格"],
E3:["es gibt + Akkusativ","第三格人称代词与 helfen / schmecken","常见强变化动词现在时"],
E4:["第四格基础使用","购物数量与量词表达","kein / nichts 否定"],
E5:["可分动词现在时","时间与地点表达","in / an / auf / nach / zu / von / aus","可分动词句中位置"],
E6:["第三格动词","固定介词与格","nicht ..., sondern ...","nicht nur ..., sondern auch ...","zwar ..., aber ..."],
E7:["Perfekt 基本结构","haben / sein 的选择","规则/不规则 Partizip II","-ieren 不加 ge-","可分/不可分前缀","sein / haben 的 Präteritum"],
E8:["Wo / Wohin 与 Wechselpräpositionen","静态位置与方向的 Dativ / Akkusativ","nach Hause / zu Hause","sorgen für / führen zu / überzeugen von / überreden zu","问路与地点表达"]
};

var GB={
E1:[["Ich ___ Deutsch.","lerne",["lernt","lernen","lernst"]],["Wir ___ Studenten.","sind",["seid","ist","bin"]],["___ bin Studentin.","Ich",["Mich","Mir","Mein"]]],
E2:[["Das ist ___ Problem.","kein",["keine","keinen","nicht"]],["Er ___ gern Bücher.（lesen）","liest",["lese","lesen","liest"]],["Das ist ___ Buch.（ich）","mein",["meine","meinen","meiner"]]],
E3:[["In der Stadt gibt es ___ Bibliothek.","eine",["ein","einer","einen"]],["Ich helfe ___.（du）","dir",["dich","du","dein"]],["Er ___ zu Mittag.（essen）","isst",["esse","esst","essen"]]],
E4:[["Ich probiere ___ Apfel.","den",["der","dem","des"]],["eine ___ Milch","Packung",["Stück","Flasche","Tüte"]],["Ich brauche ___.","nichts",["kein","keine","nicht"]]],
E5:[["Ich ___ früh ___.（aufstehen）","stehe / auf",["aufstehe / stehe","stehe / an","auf / stehe"]],["Wir treffen uns ___ 8 Uhr.","um",["am","in","nach"]],["Ich komme ___ China.","aus",["von","nach","zu"]]],
E6:[["Das Buch gehört ___.（ich）","mir",["mich","mein","ich"]],["Ich habe Angst ___ etwas.","vor",["für","auf","mit"]],["Er trinkt nicht Kaffee, ___ Tee.","sondern",["aber","oder","und"]],["Sie ist zwar müde, ___ sie arbeitet weiter.","aber",["sondern","und","oder"]]],
E7:[["Ich ___ Deutsch ___.（lernen）","habe / gelernt",["bin / gelernt","habe / lernen","bin / lernen"]],["Wir ___ nach Berlin gefahren.","sind",["haben","waren","hatten"]],["studieren →","studiert",["gestudiert","studieren","studierte"]],["besuchen →","besucht",["gebesucht","besuchen","besuchte"]],["einladen →","eingeladen",["geeinladen","einladet","eingeladet"]],["sein 的 ich-Präteritum：","war",["bin","hatte","wurde"]]],
E8:[["Ich stelle das Buch ___ Tisch.","auf den",["auf dem","an der","in der"]],["Das Buch liegt ___ Tisch.","auf dem",["auf den","in den","an die"]],["Ich gehe ___ Hause.","nach",["zu","in","an"]],["Ich bin ___ Hause.","zu",["nach","in","an"]],["Das führt ___ Problemen.","zu",["für","von","auf"]],["Er überzeugt mich ___ seiner Idee.","von",["zu","für","mit"]]]
};

function gq(u,g){var A=GB[u]||[];if(!A.length)return null;var x=A[Math.floor(Math.random()*A.length)];return{unit:u,category:"语法",type:"choice",skill:u+"-"+g,q:x[0],opts:sh([x[1]].concat(x[2])),correctText:x[1],e:"围绕该单元固定知识点生成的变式题。",generated:true}}
function vq(u){var P=pool(u);if(!P.length)return null;var q=P[Math.floor(Math.random()*P.length)],z=vp(q.raw),de=Math.random()<.5,ans=de?z.zh:z.de,vals=[],seen={};seen[ans]=1;for(var i=0;i<P.length&&vals.length<3;i++){var v=P[Math.floor(Math.random()*P.length)],x=vp(v.raw),a=de?x.zh:x.de;if(a&&!seen[a]){seen[a]=1;vals.push(a)}}return{unit:q.unit,category:"词汇",type:"choice",skill:q.unit+"-词汇记忆",q:de?"“"+z.de+"”的意思是：":"“"+z.zh+"”对应的德语是：",opts:sh([ans].concat(vals)),correctText:ans,e:"词条来自你提供的词库："+z.de+" = "+z.zh+"。",generated:true}}
function makeSet(n,u,mode){var U=u==="ALL"?Object.keys(UG):[u],S=[],O=[],weak=Object.keys(state.skills||{}).filter(function(k){return(state.skills[k].wrong||0)>0});U.forEach(function(x){(UG[x]||[]).forEach(function(g){S.push([x,g])})});for(var i=0;i<n*5&&O.length<n;i++){if(mode==="vocab"||(mode==="mixed"&&Math.random()<.35)){var v=vq(u);if(v)O.push(v);continue}var p;if(mode==="weak"&&weak.length){var w=weak[Math.floor(Math.random()*weak.length)];p=[w.slice(0,2),w.slice(3)]}else p=S[Math.floor(Math.random()*S.length)];var q=p?gq(p[0],p[1]):null;if(q)O.push(q)}return sh(O).slice(0,n)}

window.startDynamicPractice=function(){var u=document.getElementById("dynamicUnit").value,n=+document.getElementById("dynamicCount").value,m=document.getElementById("dynamicMode").value,q=makeSet(n,u,m);if(!q.length){alert("当前资料范围暂时没有足够可生成的题目；E9–E10 请先补充原始材料。");return}session={queue:q,pos:0,correct:0,mode:"dynamic",current:null,answered:false};go("quiz");showDyn()}}
window.startSmartQuiz=function(){var q=makeSet(10,"ALL","weak");session={queue:q,pos:0,correct:0,mode:"dynamic",current:null,answered:false};go("quiz");showDyn()}}
function showDyn(){if(session.pos>=session.queue.length){document.getElementById("qtext").textContent="本轮完成 🎉";document.getElementById("options").innerHTML="";document.getElementById("feedback").innerHTML='<div class="answer ok"><b>'+session.correct+" / "+session.queue.length+'</b><br>下一轮会重新组合题目。</div>';document.getElementById("progress").textContent="完成";return}var q=session.queue[session.pos];session.current=q;session.answered=false;document.getElementById("qtype").textContent=q.category+" · 自动生成";document.getElementById("progress").textContent=(session.pos+1)+" / "+session.queue.length;document.getElementById("qtext").textContent=q.q;document.getElementById("feedback").innerHTML="";document.getElementById("options").innerHTML=q.opts.map(function(o,i){return'<button class="option" onclick="answerDyn('+i+')">'+eh(o)+'</button>'}).join("");document.getElementById("nextBtn").disabled=true}
window.answerDyn=function(i){if(session.answered)return;var q=session.current,ok=i===q.opts.indexOf(q.correctText);session.answered=true;state.total++;state.correct+=ok?1:0;state.wrong+=ok?0:1;state.skills[q.skill]=state.skills[q.skill]||{right:0,wrong:0,streak:0};var st=state.skills[q.skill];if(ok){st.right++;st.streak++}else{st.wrong++;st.streak=0}updateSchedule(q.skill,ok);if(!ok){state.mistakes.unshift({time:new Date().toISOString(),unit:q.unit,skill:q.skill,q:q.q,correct:q.correctText,user:q.opts[i],explanation:q.e,generated:true});state.mistakes=state.mistakes.slice(0,200)}saveState();document.querySelectorAll("#options .option").forEach(function(b,j){if(j===q.opts.indexOf(q.correctText))b.classList.add("correct");if(j===i&&!ok)b.classList.add("wrong");b.disabled=true});document.getElementById("feedback").innerHTML='<div class="answer '+(ok?"ok":"bad")+'"><b>'+(ok?"✓ 正确":"✗ 错误")+'</b><br>'+(ok?"":"<b>正确答案：</b>"+eh(q.correctText)+"<br>")+eh(q.e)+'</div>';session.correct+=ok?1:0;document.getElementById("nextBtn").disabled=false}
window.nextQuestion=function(){if(session.mode==="dynamic"){if(session.current&&session.answered){session.pos++;showDyn()}return}if(!session.current||!session.answered)return;session.pos++;showQuestion()}

function initDynamic(){normalizeUnits();hideGrammar();visual();
var learn=document.getElementById("learn");if(learn){learn.innerHTML='<div class="card hero-card"><div class="eyebrow">ADAPTIVE PRACTICE · 自动出题</div><h2>学习中心</h2><p class="muted">不再使用固定题库。选择范围、题量和模式后，系统按固定知识点＋词库实时生成本轮题目。</p><div class="practice-config"><div><label>练习范围</label><select id="dynamicUnit"></select></div><div><label>题量</label><select id="dynamicCount"><option>5</option><option selected>10</option><option>15</option><option>20</option><option>30</option></select></div><div><label>模式</label><select id="dynamicMode"><option value="mixed">混合：语法＋词汇</option><option value="grammar">以语法为主</option><option value="vocab">以词汇为主</option><option value="weak">优先薄弱点</option></select></div></div><div id="dynamicGrammarInfo" class="grammar-summary"></div><button class="primary" onclick="startDynamicPractice()">开始生成本轮练习</button></div><div class="card"><h3>本轮固定知识范围</h3><p class="muted">E1–E2：人称代词、现在时、冠词、kein、物主冠词；E3–E5：词库支持的 Akkusativ、Dativ、强变化、可分动词和时间/地点表达；E6：Dativ、固定介词和连接结构；E7：Perfekt/Partizip II/Präteritum；E8：Wo/Wohin、Wechselpräpositionen、固定搭配。</p></div>';var e=document.getElementById("dynamicUnit");e.innerHTML='<option value="ALL">E1–E8 综合</option>'+UNIT_INFO.slice(0,8).map(function(x){return'<option value="'+x[0]+'">'+x[0]+' · '+x[1]+'</option>'}).join("");e.onchange=renderGInfo;renderGInfo()}
var words=document.getElementById("words");if(words){words.innerHTML='<div class="card hero-card"><div class="eyebrow">VOCABULARY MEMORY · 词汇记忆</div><h2>单词记背</h2><p class="muted">默认随机抽取 E1–E8，并尽量平衡单个词与短语。系统自动判断答案并记录每个词条的掌握度。</p><div class="vocab-tools"><select id="memoryUnit"></select><select id="memoryMode"><option value="de2zh">看德选中</option><option value="zh2de">看中选德</option></select><select id="memoryCount"><option>10</option><option selected>20</option><option>30</option><option>50</option></select></div><div class="memory-card"><button class="primary" onclick="startMemoryTest()">▶ 点击开始</button><div class="memory-mode" id="memoryModeLabel">看德选中</div><div class="memory-word" id="memoryWord">点击“点击开始”生成随机词汇题</div><div class="memory-answer hidden" id="memoryAnswer"></div><div id="memoryOptions" class="memory-buttons"></div><div class="memory-stat" id="memoryStat"></div></div></div><div class="card"><h3>词汇掌握度</h3><div id="vocabProgress"></div></div><div class="card"><div class="eyebrow">QUICK TRANSLATOR · 快速翻译</div><h3>德语 ↔ 中文</h3><textarea id="translatorInput" placeholder="输入德语单词、短语或句子"></textarea><div class="translator-actions"><select id="translatorPair"><option value="auto">自动判断</option><option value="de|zh-CN">德语 → 中文</option><option value="zh-CN|de">中文 → 德语</option></select><button class="primary" onclick="translateText()">翻译</button><button class="secondary" onclick="clearTranslator()">清空</button></div><div id="translatorResult" class="translation-result muted">翻译结果会显示在这里。</div><a class="translate-link" href="https://translate.google.com/?sl=de&tl=zh-CN&op=translate" target="_blank" rel="noopener">打开 Google 翻译 ↗</a></div>'];var e2=document.getElementById("memoryUnit");e2.innerHTML='<option value="ALL">全部 E1–E8</option>'+UNIT_INFO.slice(0,8).map(function(x){return'<option value="'+x[0]+'">'+x[0]+' '+x[1]+'</option>'}).join("");e2.value="ALL";resetMemory()}}
function renderGInfo(){var u=document.getElementById("dynamicUnit")?.value||"ALL",box=document.getElementById("dynamicGrammarInfo");if(!box)return;var us=u==="ALL"?Object.keys(UG):[u];box.innerHTML="<b>知识点：</b> "+us.flatMap(function(x){return UG[x]}).map(function(g){return'<span class="grammar-chip">'+eh(g)+'</span>'}).join("")}
function resetMemory(){window._mem={items:[],pos:0,score:0,answered:false,mode:document.getElementById("memoryMode")?.value||"de2zh",unit:document.getElementById("memoryUnit")?.value||"ALL",count:+(document.getElementById("memoryCount")?.value||20)};document.getElementById("memoryWord").textContent="点击“点击开始”生成随机词汇题";document.getElementById("memoryOptions").innerHTML="";document.getElementById("memoryAnswer").classList.add("hidden");document.getElementById("memoryStat").textContent="系统会自动判断。"}
function startMemoryTest(){var m=window._mem,p=pool(m.unit);m.items=sh(p).slice(0,Math.min(m.count,p.length));m.pos=0;m.score=0;showMem()}
function showMem(){var m=window._mem,q=m.items[m.pos],w=document.getElementById("memoryWord"),a=document.getElementById("memoryAnswer"),o=document.getElementById("memoryOptions");if(!q){w.textContent="本轮完成 🎉";a.textContent="正确 "+m.score+" / "+m.items.length+" · 熟练度已记录";a.classList.remove("hidden");o.innerHTML="";return}m.answered=false;var z=vp(q.raw),correct=m.mode==="de2zh"?z.zh:z.de;w.textContent=m.mode==="de2zh"?z.de:z.zh;a.classList.add("hidden");var c=[],seen={};seen[correct]=1;for(var i=0;i<30&&c.length<3;i++){var v=p[Math.floor(Math.random()*p.length)],x=vp(v.raw),t=m.mode==="de2zh"?x.zh:x.de;if(t&&!seen[t]){seen[t]=1;c.push(t)}}o.innerHTML=sh([correct].concat(c)).map(function(x){return'<button class="option" onclick=\'memAnswer(this,'+JSON.stringify(x)+')\'>'+eh(x)+'</button>'}).join("");document.getElementById("memoryModeLabel").textContent=m.mode==="de2zh"?"看德选中":"看中选德";document.getElementById("memoryStat").textContent="第 "+(m.pos+1)+" / "+m.items.length+" 题 · 选择后立即判断"}
function memAnswer(btn,val){var m=window._mem;if(m.answered)return;m.answered=true;var q=m.items[m.pos],z=vp(q.raw),correct=m.mode==="de2zh"?z.zh:z.de,ok=val===correct,st=vs(),k=vk(q),x=st[k]||{right:0,wrong:0,streak:0,mastery:0};if(ok){x.right++;x.streak++;x.mastery=Math.min(100,(x.mastery||0)+12+Math.min(x.streak,5)*2);m.score++}else{x.wrong++;x.streak=0;x.mastery=Math.max(0,(x.mastery||0)-25)}x.last=Date.now();x.due=Date.now()+(ok?86400000*Math.min(Math.max(x.streak,1),14):600000);st[k]=x;sv(st);document.querySelectorAll("#memoryOptions .option").forEach(function(b){if(b.textContent===correct)b.classList.add("correct");if(b===btn&&!ok)b.classList.add("wrong");b.disabled=true});var a=document.getElementById("memoryAnswer");a.innerHTML=(ok?"✓ 正确":"✗ 错误")+"<br><b>正确答案：</b>"+eh(correct)+"<br><span class=\'small muted\'>掌握度："+x.mastery+"%</span>";a.classList.remove("hidden");setTimeout(function(){m.pos++;showMem();renderVP()},900)}
function renderVP(){var box=document.getElementById("vocabProgress");if(!box)return;var st=vs();box.innerHTML=UNIT_INFO.slice(0,8).map(function(u){var a=FULL_VOCAB.filter(function(v){return v.unit===u[0]}),avg=a.length?Math.round(a.reduce(function(t,v){return t+mastery(st[vk(v)])},0)/a.length):0;return'<div class="skillrow"><b>'+u[0]+' · '+u[1]+'</b><br><span class="muted">平均掌握度 '+avg+'%</span><div class="scorebar" style="margin-top:7px"><i style="width:'+avg+'%"></i></div></div>'}).join("")}
function translateText(){var input=document.getElementById("translatorInput").value.trim(),out=document.getElementById("translatorResult");if(!input)return;var pair=document.getElementById("translatorPair").value;if(pair==="auto")pair=/[\u4e00-\u9fff]/.test(input)?"zh-CN|de":"de|zh-CN";out.textContent="翻译中…";fetch("https://api.mymemory.translated.net/get?q="+encodeURIComponent(input)+"&langpair="+encodeURIComponent(pair)).then(function(r){return r.json()}).then(function(d){out.textContent=(d.responseData&&d.responseData.translatedText)||"未获得翻译结果"}).catch(function(){out.textContent="在线翻译暂时不可用，请打开下方 Google 翻译。"})}
function clearTranslator(){document.getElementById("translatorInput").value="";document.getElementById("translatorResult").textContent="翻译结果会显示在这里。"}
function renderVP(){var b=document.getElementById("vocabProgress");if(!b)return;var st=vs();b.innerHTML=UNIT_INFO.slice(0,8).map(function(u){var a=FULL_VOCAB.filter(function(v){return v.unit===u[0]}),avg=a.length?Math.round(a.reduce(function(t,v){return t+mastery(st[vk(v)])},0)/a.length):0;return'<div class="skillrow"><b>'+u[0]+' · '+u[1]+'</b><br><span class="muted">平均掌握度 '+avg+'%</span><div class="scorebar" style="margin-top:7px"><i style="width:'+avg+'%"></i></div></div>'}).join("")}
initDynamic();renderVP();
})();
